# Generated by Django 2.2.7 on 2019-11-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sith',
            name='sith_planet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruits.Planet'),
        ),
    ]
