# Generated by Django 2.2.7 on 2019-11-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0002_sith_sith_planet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('answer_one', models.CharField(max_length=100)),
                ('answer_two', models.CharField(max_length=100)),
                ('cor_answer', models.BooleanField(default=True)),
                ('question_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruits.Question')),
            ],
        ),
    ]
