# Generated by Django 2.2.7 on 2019-11-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0004_auto_20191105_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='answer_one',
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='answer_two',
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='cor_answer',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='amswer_false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='answer_true',
            field=models.BooleanField(default=False),
        ),
    ]
