# Generated by Django 2.2.7 on 2019-11-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0005_auto_20191105_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequestion',
            old_name='amswer_false',
            new_name='Не правильно',
        ),
        migrations.RenameField(
            model_name='choicequestion',
            old_name='answer_true',
            new_name='Правильно',
        ),
    ]
