# Generated by Django 2.2.7 on 2019-11-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0006_auto_20191106_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequestion',
            old_name='Не правильно',
            new_name='amswer_false',
        ),
        migrations.RenameField(
            model_name='choicequestion',
            old_name='Правильно',
            new_name='answer_true',
        ),
    ]
