# Generated by Django 2.2.7 on 2019-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0007_auto_20191106_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='amswer_false',
        ),
        migrations.AddField(
            model_name='recruit',
            name='recruit_planet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='answer_true',
            field=models.CharField(max_length=100),
        ),
    ]
